# Generated by Django 2.1.7 on 2019-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exceptionlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, null=True)),
                ('lineno', models.CharField(max_length=10, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
